In [1]:
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd

In [80]:
x = [8.0, 1, 2.5, 4, 28.0]
x_with_nan = [8.0, 1, 2.5, math.nan, 4, 28.0]
print(x)
print(x_with_nan)

[8.0, 1, 2.5, 4, 28.0]
[8.0, 1, 2.5, nan, 4, 28.0]


In [82]:
x = [8.0, 1, 2.5, 4, 28.0]
x_with_nan = [8.0, 1, 2.5, math.nan, 4, 28.0]
print(x)
print(x_with_nan)

[8.0, 1, 2.5, 4, 28.0]
[8.0, 1, 2.5, nan, 4, 28.0]


In [4]:
mean_ = sum(x) / len(x)
mean_

8.7

In [5]:
mean_ = statistics.mean(x)
print(mean_)

8.7


In [6]:
mean_ = statistics.mean(x_with_nan)
print(mean_)

nan


In [7]:
mean_ = np.mean(y)
mean_

8.7

In [8]:
mean_ = y.mean()
mean_

8.7

In [9]:
print(np.mean(y_with_nan))
print(y_with_nan.mean())

nan
nan


In [10]:
np.nanmean(y_with_nan)

8.7

In [11]:
mean_ = z.mean()
mean_

8.7

In [12]:
z_with_nan.mean()

8.7

In [13]:
x = [8.0, 1, 2.5, 4, 28.0]
w = [0.1, 0.2, 0.3, 0.25, 0.15]

wmean = sum(w[i] * x[i] for i in range(len(x))) / sum(w)
print(wmean)

wmean = sum(x_ * w_ for (x_, w_) in zip(x, w)) / sum(w)
print(wmean)

6.95
6.95


In [14]:
y, z, w = np.array(x), pd.Series(x), np.array(w)

wmean = np.average(y, weights=w)
print(wmean)

wmean = np.average(z, weights=w)
print(wmean)

6.95
6.95


In [15]:
(w * y).sum() / w.sum()

6.95

In [16]:
hmean = len(x) / sum(1 / item for item in x)
hmean

2.7613412228796843

In [17]:
hmean = statistics.harmonic_mean(x)
hmean

2.7613412228796843

In [18]:
scipy.stats.hmean(y)

2.7613412228796843

In [19]:
scipy.stats.hmean(z)

2.7613412228796843

In [20]:
gmean = 1

for item in x:
    gmean *= item

gmean **= 1 / len(x)
gmean

4.677885674856041

In [21]:
scipy.stats.gmean(y)

4.67788567485604

In [22]:
scipy.stats.gmean(z)

4.67788567485604

In [23]:
n = len(x)
if n % 2:
    median_ = sorted(x)[round(0.5*(n-1))]
else:
    x_ord, index = sorted(x), round(0.5 * n)
    median_ = 0.5 * (x_ord[index-1] + x_ord[index])

median_

4

In [24]:
x

[8.0, 1, 2.5, 4, 28.0]

In [25]:
statistics.median_low(x[:-1])

2.5

In [26]:
statistics.median_high(x[:-1])

4

In [27]:
print(statistics.median(x_with_nan))
print(statistics.median_low(x_with_nan))
print(statistics.median_high(x_with_nan))

6.0
4
8.0


In [28]:
median_ = np.median(y)
print(median_)

4.0


In [29]:
median_ = np.median(y[:-1])
print(median_)

3.25


In [30]:
u = [2, 3, 2, 8, 12]

v = [12, 15, 12, 15, 21, 15, 12]

mode_ = max((u.count(item), item) for item in set(u))[1]
mode_

2

In [31]:
mode_ = statistics.mode(u)
mode_

2

In [32]:
u, v = np.array(u), np.array(v)

mode_ = scipy.stats.mode(u)
mode_

ModeResult(mode=array([2]), count=array([2]))

In [33]:
mode_ = scipy.stats.mode(v)
mode_

ModeResult(mode=array([12]), count=array([3]))

In [34]:
print(mode_.mode)
print(mode_.count)

[12]
[3]


In [35]:
u, v, w = pd.Series(u), pd.Series(v), pd.Series([2, 2, math.nan])

print(u.mode())

print(v.mode())

print(w.mode())

0    2
dtype: int32
0    12
1    15
dtype: int32
0    2.0
dtype: float64


In [36]:
n = len(x)

mean_ = sum(x) / n

var_ = sum((item - mean_)**2 for item in x) / (n - 1)
var_

123.19999999999999

In [37]:
var_ = statistics.variance(x)
var_

123.2

In [38]:
var_ = np.var(y, ddof=1)
var_

123.19999999999999

In [39]:
var_ = y.var(ddof=1)
var_

123.19999999999999

In [40]:
z.var(ddof=1)

123.19999999999999

In [41]:
std_ = var_ ** 0.5
std_

11.099549540409285

In [42]:
std_ = statistics.stdev(x)
std_

11.099549540409287

In [43]:
np.std(y, ddof=1)

11.099549540409285

In [44]:
y.std(ddof=1)

11.099549540409285

In [45]:
z.std(ddof=1)

11.099549540409285

In [46]:
x = [8.0, 1, 2.5, 4, 28.0]

n = len(x)

mean_ = sum(x) / n
var_ = sum((item - mean_)**2 for item in x) / (n-1)
std_ = var_ ** 0.5

skew_ = (sum((item - mean_)**3 for item in x) * n / ((n - 1) * (n - 2) * std_**3))

In [47]:
skew_

1.9470432273905929

In [48]:
y, y_with_nan = np.array(x), np.array(x_with_nan)

scipy.stats.skew(y, bias=False)

1.9470432273905927

In [49]:
scipy.stats.skew(y_with_nan, bias=False)

nan

In [50]:
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan)

z.skew()

1.9470432273905924

In [51]:
z_with_nan.skew()

1.9470432273905924

In [52]:
>>> x = [-5.0, -1.1, 0.1, 2.0, 8.0, 12.8, 21.0, 25.8, 41.0]
>>> statistics.quantiles(x, n=2)
[8.0]
>>> statistics.quantiles(x, n=4, method='inclusive')
[0.1, 8.0, 21.0]

[0.1, 8.0, 21.0]

In [53]:
>>> y = np.array(x)
>>> np.percentile(y, 5)
-3.44
>>> np.percentile(y, 95)
34.919999999999995

34.919999999999995

In [59]:
np.percentile(y, [25, 50, 75])

array([ 0.1,  8. , 21. ])

In [60]:
np.median(y)

8.0

In [61]:
>>> y_with_nan = np.insert(y, 2, np.nan)
>>> y_with_nan

array([-5. , -1.1,  nan,  0.1,  2. ,  8. , 12.8, 21. , 25.8, 41. ])

In [62]:
np.nanpercentile(y_with_nan, [25, 50, 75])

array([ 0.1,  8. , 21. ])

In [63]:
np.nanpercentile(y_with_nan, [25, 50, 75])

array([ 0.1,  8. , 21. ])

In [64]:
np.quantile(y, 0.05)


-3.44

In [65]:
np.quantile(y, 0.95)

34.919999999999995

In [66]:
np.quantile(y, [0.25, 0.5, 0.75])

array([ 0.1,  8. , 21. ])

In [67]:
np.nanquantile(y_with_nan, [0.25, 0.5, 0.75])

array([ 0.1,  8. , 21. ])

In [68]:
>>> z, z_with_nan = pd.Series(y), pd.Series(y_with_nan)
>>> z.quantile(0.05)

-3.44

In [69]:
>>> z.quantile(0.95)

34.919999999999995

In [70]:
>>> z.quantile([0.25, 0.5, 0.75])

0.25     0.1
0.50     8.0
0.75    21.0
dtype: float64

In [71]:
>>> z_with_nan.quantile([0.25, 0.5, 0.75])

0.25     0.1
0.50     8.0
0.75    21.0
dtype: float64

In [72]:
np.ptp(y)

46.0

In [73]:
np.ptp(z)

46.0

In [74]:
np.ptp(y_with_nan)

nan

In [75]:
np.ptp(z_with_nan)

nan

In [76]:
np.amax(y) - np.amin(y)

46.0

In [77]:
>>> quartiles = np.quantile(y, [0.25, 0.75])
>>> quartiles[1] - quartiles[0]

20.9

In [78]:
>>> result = scipy.stats.describe(y, ddof=1, bias=False)
>>> result

DescribeResult(nobs=9, minmax=(-5.0, 41.0), mean=11.622222222222222, variance=228.75194444444446, skewness=0.9249043136685094, kurtosis=0.14770623629658886)