In [2]:
import numpy as np

mulai = int(input("mulai :"))
selesai = int(input("selesai :"))
a = np.arange(mulai,selesai,1)
b = a.reshape(3,int(selesai/3))
c = b.reshape (3,3,3) 

print ("1 DIMENSI")
print (a)
print ("2 DIMENSI")
print (b)
print ("3 DIMENSI")
print (c)

mulai :1
selesai :28
1 DIMENSI
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
2 DIMENSI
[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]]
3 DIMENSI
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [14]:
import numpy as np
from numpy import random

Data = int(input("Banyak Data :"))
Mulai = int(input("Mulai :"))
Selesai = int(input("Selesai :"))

#print()

a = np.random.randint(Mulai, Selesai, Data)
b = a.reshape(4,4)
c = b[:, ::-1]

print("Bangkitkan Array 1 Dimensi Dari Random Integer")
print (a)
print ("DUA DIMENSI")
print (b)
print ("TUKAR POSISI")
print (c)

Banyak Data :16
Mulai :1
Selesai :50
Bangkitkan Array 1 Dimensi Dari Random Integer
[21 43 49 37 44 21 28 37 17 10 21 35 12 23 19 27]
DUA DIMENSI
[[21 43 49 37]
 [44 21 28 37]
 [17 10 21 35]
 [12 23 19 27]]
TUKAR POSISI
[[37 49 43 21]
 [37 28 21 44]
 [35 21 10 17]
 [27 19 23 12]]


In [7]:
x = np.ones((10,10))*4
x[1:-1, 1:-1] = 0
x

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])