In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
import numpy as np

a = np.array([1, 2, 3])

In [4]:
a

array([1, 2, 3])

In [5]:
# you can easily create an array filled with 0s:

np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [6]:
# Or an array filled with 1s:

np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [7]:
# Or even an empty array!
# The function empty creates an array whose initial content is random and depends on the state of the memory.

np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [8]:
# You can create an array with a range of elements

print(np.arange(4))
print(np.arange(0,10,2)) # (start, stop, step)

[0 1 2 3]
[0 2 4 6 8]


In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [13]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [14]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [16]:
array_example.ndim

3

In [17]:
array_example.size

24

In [18]:
array_example.size

24

In [19]:
array_example.shape

(3, 2, 4)

In [20]:
arr_one = np.array([[1, 2, 3, 4, 5]])

In [21]:
arr_one.ndim

2

In [22]:
arr_one.size

5

In [23]:
arr_one.shape

(1, 5)

In [24]:
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [25]:
b = a.reshape(3,2)

print(b)

[[0 1]
 [2 3]
 [4 5]]


In [26]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [27]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [28]:
# You can use np.newaxis to add a new axis:

a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [29]:
# You can convert a 1D array to a row vector by inserting an axis along the first dimension

row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [30]:
# for a column vector, You can insert an axis along the second dimension

col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [31]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [32]:
# You can use np.expand_dims to add an axis at index position 1 with:

b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [33]:
# You can add an axis at index position 0 with:

c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [34]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [35]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
# You can easily print all of the values in the array that are less than 5

print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [43]:
five_up = (a >= 5)

print(a[five_up])
print(a[a>=5])

a

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
# You can select elements that are divisible by 2

divisible_by_2 = a[a%2==0]

print(divisible_by_2)

[ 2  4  6  8 10 12]


In [45]:
# you can select elements that satisfy two conditions using the & and | operators

c = a[(a > 2) & (a < 11)]

print(c)

[ 3  4  5  6  7  8  9 10]


In [46]:
arr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [49]:
a_1 = np.array([[1, 1],
                [2, 2]])

In [50]:
a_2 = np.array([[3, 3],
                [4, 4]])

In [51]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [52]:
# Or stack them horizontally with hstack

np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [54]:
arrsplit = np.array([[1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
                     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [55]:
# If you wanted to split this array into three equally shaped arrays

np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [56]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
# You can create a new array object that looks at the same data

b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
# Using the copy method will make a complete copy of the array and its data (a deep copy).

c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [59]:
a = np.array([1, 2, 3, 4])

# Add all of the elements in the array
a.sum()

10

In [60]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [61]:
# You can sum the rows

b.sum(axis=0)

array([3, 3])

In [62]:
# You can sum the columns

b.sum(axis=1)

array([2, 4])

In [63]:
data = np.array([1, 2])
data

array([1, 2])

In [69]:
ones = np.ones(2)
ones


array([1., 1.])

In [70]:
data

array([1, 2])

In [71]:
data + ones

array([2., 3.])

In [72]:
data * data

array([1, 4])

In [73]:
data / data

array([1., 1.])

In [74]:
data / ones

array([1., 2.])

In [75]:
data * 2

array([2, 4])

In [76]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [78]:
A.sum()

4.8595784

In [79]:
A.min()

0.05093587

In [80]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [81]:
A.max()

0.82485143

In [82]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [83]:
A.std()

0.21392120766089617

In [88]:
np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))

print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.87063564 0.27194638]
 [0.14016313 0.78143224]
 [0.84272973 0.02142102]]


In [89]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [90]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [91]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [92]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [93]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [96]:
a_1

array([[1, 2, 3],
       [4, 5, 6]])

In [97]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


In [98]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [100]:
print(data.max())
print(data.min())
print(data.sum())
print(data.max(axis=0))
print(data.max(axis=1))

6
1
21
[5 6]
[2 4 6]


In [101]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [102]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [105]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [107]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


In [108]:
ndarr = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [109]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [110]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [111]:
print(np.random.random((4,3,2)))

[[[0.17334753 0.34190582]
  [0.46117329 0.31047939]
  [0.64811198 0.12027268]]

 [[0.79605805 0.89343263]
  [0.53749522 0.51797329]
  [0.13207225 0.11136164]]

 [[0.09735032 0.90565386]
  [0.91106028 0.80525982]
  [0.55920346 0.8505693 ]]

 [[0.63205824 0.4405202 ]
  [0.38358729 0.05544369]
  [0.71350625 0.93585573]]]


In [112]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [113]:
# You can use flatten to flatten your array into a 1D array.

arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [155]:
import numpy as np

mulai = int(input("mulai :"))
selesai = int(input("selesai :"))
a = np.arange(mulai,selesai,1)
b = a.reshape(3,int(selesai/3))
c = b.reshape (3,int(selesai/3)) #(3,3,int(selesai/9)

print ("1 DIMENSI")
print (a)
print ("2 DIMENSI")
print (b)


mulai :1
selesai :28
1 DIMENSI
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
2 DIMENSI
[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]]


In [148]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [149]:
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [146]:
import numpy as np

mulai = int(input("mulai :"))
selesai = int(input("selesai :"))
a = np.arange(mulai,selesai,1)


mulai :2
selesai :28


In [156]:
c

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [186]:
import numpy as np
from random import randint
from random import seed

banyak_data = int(input("banyak data :"))
mulai = int(input("mulai :"))
selesai = int(input("selesai :"))

# generate some integers
for _ in range(banyak_data):
a = randint (mulai, seleasi)

#a = randint(banyak_data,selesai-mulai)

print ("Bangkitkan Array 1 Dimensi dari Random Integer")
print (a)

IndentationError: expected an indented block (3547135527.py, line 11)

In [189]:
x = np.ones((10,10))*4
x

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [191]:
x[1:-1, 1:-1] = 0
x

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [ ]:
x